class_name BattleHeroRegistry
extends RefCounted

## 英雄 hook 注册表（Logic 层）— 照源 unit.lua:216 `require(info.Script)` 的 Godot 等价（Phase 2.7）。
## Godot 等价：预 new 英雄 hook 实例缓存（避 74 class_name 解析时序），按 Script 路径分发 apply(hero)。
## 英雄脚本 extends RefCounted + apply(hero)，apply 内注册 hero_hooks（技能/单位/buff 分发 key → Callable）。
## View 表现（popup/effect/shader/音效）分层 Phase 4；本注册表仅 Logic hook。

const HeroViper = preload("res://scripts/systems/battle/heroes/hero_viper.gd")
const HeroSil = preload("res://scripts/systems/battle/heroes/hero_sil.gd")
const HeroOD = preload("res://scripts/systems/battle/heroes/hero_od.gd")
const HeroAV = preload("res://scripts/systems/battle/heroes/hero_av.gd")
const HeroMortar = preload("res://scripts/systems/battle/heroes/hero_mortar.gd")
const HeroGorilla = preload("res://scripts/systems/battle/heroes/hero_gorilla.gd")
const HeroArcher = preload("res://scripts/systems/battle/heroes/hero_archer.gd")
const HeroDR = preload("res://scripts/systems/battle/heroes/hero_dr.gd")
const HeroPugna = preload("res://scripts/systems/battle/heroes/hero_pugna.gd")
const HeroRazor = preload("res://scripts/systems/battle/heroes/hero_razor.gd")
const HeroHuskar = preload("res://scripts/systems/battle/heroes/hero_huskar.gd")
const HeroQOP = preload("res://scripts/systems/battle/heroes/hero_qop.gd")
const HeroPanda = preload("res://scripts/systems/battle/heroes/hero_panda.gd")
const HeroCW = preload("res://scripts/systems/battle/heroes/hero_cw.gd")
const HeroPOM = preload("res://scripts/systems/battle/heroes/hero_pom.gd")
const HeroAxe = preload("res://scripts/systems/battle/heroes/hero_axe.gd")
const HeroOM = preload("res://scripts/systems/battle/heroes/hero_om.gd")
const HeroLich = preload("res://scripts/systems/battle/heroes/hero_lich.gd")
const HeroJUGG = preload("res://scripts/systems/battle/heroes/hero_jugg.gd")
const HeroCoco = preload("res://scripts/systems/battle/heroes/hero_coco.gd")
const HeroAM = preload("res://scripts/systems/battle/heroes/hero_am.gd")
const HeroBone = preload("res://scripts/systems/battle/heroes/hero_bone.gd")
const HeroFootman = preload("res://scripts/systems/battle/heroes/hero_footman.gd")
const HeroLOA = preload("res://scripts/systems/battle/heroes/hero_loa.gd")
const HeroSorceress = preload("res://scripts/systems/battle/heroes/hero_sorceress.gd")
const HeroSNK = preload("res://scripts/systems/battle/heroes/hero_snk.gd")
const HeroEnch = preload("res://scripts/systems/battle/heroes/hero_ench.gd")
const HeroSP = preload("res://scripts/systems/battle/heroes/hero_sp.gd")
const HeroTHD = preload("res://scripts/systems/battle/heroes/hero_thd.gd")
const HeroVS = preload("res://scripts/systems/battle/heroes/hero_vs.gd")
const HeroSniper = preload("res://scripts/systems/battle/heroes/hero_sniper.gd")
const HeroSuicideGoblinjr = preload("res://scripts/systems/battle/heroes/hero_suicidegoblinjr.gd")
const HeroNEC = preload("res://scripts/systems/battle/heroes/hero_nec.gd")
const HeroTiny = preload("res://scripts/systems/battle/heroes/hero_tiny.gd")
const HeroLuna = preload("res://scripts/systems/battle/heroes/hero_luna.gd")
const HeroMed = preload("res://scripts/systems/battle/heroes/hero_med.gd")
const HeroSF = preload("res://scripts/systems/battle/heroes/hero_sf.gd")
const HeroSpider = preload("res://scripts/systems/battle/heroes/hero_spider.gd")
const HeroSilverDragon = preload("res://scripts/systems/battle/heroes/hero_silverdragon.gd")
const HeroWD = preload("res://scripts/systems/battle/heroes/hero_wd.gd")
const HeroTroll = preload("res://scripts/systems/battle/heroes/hero_troll.gd")
const HeroAncientTreant = preload("res://scripts/systems/battle/heroes/hero_ancienttreant.gd")
const HeroKOTL = preload("res://scripts/systems/battle/heroes/hero_kotl.gd")
const HeroTA = preload("res://scripts/systems/battle/heroes/hero_ta.gd")
const HeroDP = preload("res://scripts/systems/battle/heroes/hero_dp.gd")
const HeroTK = preload("res://scripts/systems/battle/heroes/hero_tk.gd")
const HeroNecromancersr = preload("res://scripts/systems/battle/heroes/hero_necromancersr.gd")
const HeroWL = preload("res://scripts/systems/battle/heroes/hero_wl.gd")
const HeroTB = preload("res://scripts/systems/battle/heroes/hero_tb.gd")
const HeroPL = preload("res://scripts/systems/battle/heroes/hero_pl.gd")
const HeroTitanHead = preload("res://scripts/systems/battle/heroes/hero_titanhead.gd")
const HeroBossSil = preload("res://scripts/systems/battle/heroes/hero_bosssil.gd")
const HeroBossCoco = preload("res://scripts/systems/battle/heroes/hero_bosscoco.gd")
const HeroBossHuskar = preload("res://scripts/systems/battle/heroes/hero_bosshuskar.gd")
const HeroBossKOTL = preload("res://scripts/systems/battle/heroes/hero_bosskotl.gd")
const HeroExSilverDragon = preload("res://scripts/systems/battle/heroes/hero_exsilverdragon.gd")
const HeroExBossHuskar = preload("res://scripts/systems/battle/heroes/hero_exbosshuskar.gd")
const HeroExBossSpider = preload("res://scripts/systems/battle/heroes/hero_exbossspider.gd")
const HeroBossTB = preload("res://scripts/systems/battle/heroes/hero_bosstb.gd")
const HeroExLoz = preload("res://scripts/systems/battle/heroes/hero_exloz.gd")
const HeroSB = preload("res://scripts/systems/battle/heroes/hero_sb.gd")
const HeroMarine = preload("res://scripts/systems/battle/heroes/hero_marine.gd")
const HeroPhoenix = preload("res://scripts/systems/battle/heroes/hero_phoenix.gd")
const HeroBB = preload("res://scripts/systems/battle/heroes/hero_bb.gd")
const HeroExPhoenix = preload("res://scripts/systems/battle/heroes/hero_exphoenix.gd")
const HeroKael = preload("res://scripts/systems/battle/heroes/hero_kael.gd")
const HeroLina = preload("res://scripts/systems/battle/heroes/hero_lina.gd")
const HeroOK = preload("res://scripts/systems/battle/heroes/hero_ok.gd")
const HeroTH = preload("res://scripts/systems/battle/heroes/hero_th.gd")
const HeroUrsa = preload("res://scripts/systems/battle/heroes/hero_ursa.gd")
const HeroNaga = preload("res://scripts/systems/battle/heroes/hero_naga.gd")

static var _cache: Dictionary = {}
static var _initialized: bool = false


static func _ensure_init() -> void:
	if _initialized:
		return
	_cache["battle/heroes/Viper"] = HeroViper.new()
	_cache["battle/heroes/Sil"] = HeroSil.new()
	_cache["battle/heroes/OD"] = HeroOD.new()
	_cache["battle/heroes/AV"] = HeroAV.new()
	_cache["battle/heroes/Mortar"] = HeroMortar.new()
	_cache["battle/heroes/Gorilla"] = HeroGorilla.new()
	_cache["battle/heroes/Archer"] = HeroArcher.new()
	_cache["battle/heroes/DR"] = HeroDR.new()
	_cache["battle/heroes/Pugna"] = HeroPugna.new()
	_cache["battle/heroes/Razor"] = HeroRazor.new()
	_cache["battle/heroes/Huskar"] = HeroHuskar.new()
	_cache["battle/heroes/QOP"] = HeroQOP.new()
	_cache["battle/heroes/Panda"] = HeroPanda.new()
	_cache["battle/heroes/CW"] = HeroCW.new()
	_cache["battle/heroes/POM"] = HeroPOM.new()
	_cache["battle/heroes/Axe"] = HeroAxe.new()
	_cache["battle/heroes/OM"] = HeroOM.new()
	_cache["battle/heroes/Lich"] = HeroLich.new()
	_cache["battle/heroes/JUGG"] = HeroJUGG.new()
	_cache["battle/heroes/Coco"] = HeroCoco.new()
	_cache["battle/heroes/AM"] = HeroAM.new()
	_cache["battle/heroes/Bone"] = HeroBone.new()
	_cache["battle/heroes/Footman"] = HeroFootman.new()
	_cache["battle/heroes/LOA"] = HeroLOA.new()
	_cache["battle/heroes/Sorceress"] = HeroSorceress.new()
	_cache["battle/heroes/SNK"] = HeroSNK.new()
	_cache["battle/heroes/Ench"] = HeroEnch.new()
	_cache["battle/heroes/SP"] = HeroSP.new()
	_cache["battle/heroes/THD"] = HeroTHD.new()
	_cache["battle/heroes/VS"] = HeroVS.new()
	_cache["battle/heroes/Sniper"] = HeroSniper.new()
	_cache["battle/heroes/SuicideGoblinjr"] = HeroSuicideGoblinjr.new()
	_cache["battle/heroes/NEC"] = HeroNEC.new()
	_cache["battle/heroes/Tiny"] = HeroTiny.new()
	_cache["battle/heroes/Luna"] = HeroLuna.new()
	_cache["battle/heroes/Med"] = HeroMed.new()
	_cache["battle/heroes/SF"] = HeroSF.new()
	_cache["battle/heroes/Spider"] = HeroSpider.new()
	_cache["battle/heroes/SilverDragon"] = HeroSilverDragon.new()
	_cache["battle/heroes/WD"] = HeroWD.new()
	_cache["battle/heroes/Troll"] = HeroTroll.new()
	_cache["battle/heroes/AncientTreant"] = HeroAncientTreant.new()
	_cache["battle/heroes/KOTL"] = HeroKOTL.new()
	_cache["battle/heroes/TA"] = HeroTA.new()
	_cache["battle/heroes/DP"] = HeroDP.new()
	_cache["battle/heroes/TK"] = HeroTK.new()
	_cache["battle/heroes/Necromancersr"] = HeroNecromancersr.new()
	_cache["battle/heroes/WL"] = HeroWL.new()
	_cache["battle/heroes/TB"] = HeroTB.new()
	_cache["battle/heroes/PL"] = HeroPL.new()
	_cache["battle/heroes/TitanHead"] = HeroTitanHead.new()
	_cache["battle/heroes/BossSil"] = HeroBossSil.new()
	_cache["battle/heroes/BossCoco"] = HeroBossCoco.new()
	_cache["battle/heroes/BossHuskar"] = HeroBossHuskar.new()
	_cache["battle/heroes/BossKOTL"] = HeroBossKOTL.new()
	_cache["battle/heroes/ExSilverDragon"] = HeroExSilverDragon.new()
	_cache["battle/heroes/ExBossHuskar"] = HeroExBossHuskar.new()
	_cache["battle/heroes/ExBossSpider"] = HeroExBossSpider.new()
	_cache["battle/heroes/BossTB"] = HeroBossTB.new()
	_cache["battle/heroes/ExLoz"] = HeroExLoz.new()
	_cache["battle/heroes/SB"] = HeroSB.new()
	_cache["battle/heroes/Marine"] = HeroMarine.new()
	_cache["battle/heroes/Phoenix"] = HeroPhoenix.new()
	_cache["battle/heroes/BB"] = HeroBB.new()
	_cache["battle/heroes/ExPhoenix"] = HeroExPhoenix.new()
	_cache["battle/heroes/Kael"] = HeroKael.new()
	_cache["battle/heroes/Lina"] = HeroLina.new()
	_cache["battle/heroes/OK"] = HeroOK.new()
	_cache["battle/heroes/TH"] = HeroTH.new()
	_cache["battle/heroes/Ursa"] = HeroUrsa.new()
	_cache["battle/heroes/Naga"] = HeroNaga.new()
	_initialized = true


static func apply(script_path: String, hero: Variant) -> void:
	_ensure_init()
	var inst: Variant = _cache.get(script_path, null)
	if inst != null:
		inst.apply(hero)


# 实现读 proto._awake（HeroInstance.awake 养成控制，stage_manager 构建 proto 时注入）。
# 召唤物/怪物 proto 无 _awake 键 → 默认 false（不觉醒）。
static func proto_awake(proto: Dictionary) -> bool:
	return bool(proto.get("_awake", false))
